# Generated by Django 5.0.6 on 2024-07-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=250)),
                ('prod_desc', models.CharField(max_length=550)),
                ('prod_quantity', models.IntegerField()),
                ('prod_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prod_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
